import localFont from "next/font/local";
// components
import { ThemeProvider } from "@/components/theme-provider";
// style
import "./globals.css";

const vazirmatn = localFont({
  src: [
    {
      path: "./fonts/vazirmatn-thin.woff2",
      variable: "--font-vazirmatn",
      weight: "100",
      style: "normal",
      display: "swap",
    },
    {
      path: "./fonts/vazirmatn-extraLight.woff2",
      variable: "--font-vazirmatn",
      weight: "200",
      style: "normal",
      display: "swap",
    },
    {
      path: "./fonts/vazirmatn-light.woff2",
      variable: "--font-vazirmatn",
      weight: "300",
      style: "normal",
      display: "swap",
    },
    {
      path: "./fonts/vazirmatn-regular.woff2",
      variable: "--font-vazirmatn",
      weight: "400",
      style: "normal",
      display: "swap",
    },
    {
      path: "./fonts/vazirmatn-medium.woff2",
      variable: "--font-vazirmatn",
      weight: "500",
      style: "normal",
      display: "swap",
    },
    {
      path: "./fonts/vazirmatn-semiBold.woff2",
      variable: "--font-vazirmatn",
      weight: "600",
      style: "normal",
      display: "swap",
    },
    {
      path: "./fonts/vazirmatn-bold.woff2",
      variable: "--font-vazirmatn",
      weight: "700",
      style: "normal",
      display: "swap",
    },
    {
      path: "./fonts/vazirmatn-extraBold.woff2",
      variable: "--font-vazirmatn",
      weight: "800",
      style: "normal",
      display: "swap",
    },
    {
      path: "./fonts/vazirmatn-black.woff2",
      variable: "--font-vazirmatn",
      weight: "900",
      style: "normal",
      display: "swap",
    },
  ],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl" suppressHydrationWarning>
      <body className={`${vazirmatn.className} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
